# Change these first
owner: ReArmedHalo # Your GitHub organization or username, where this repository lives
repo: holonet-status # The name of this repository

sites:
  - name: Dashboard
    url: https://holonet.us
  - name: Plex
    url: $PLEX_VIA_PORT
  - name: Overseerr
    url: https://overseerr.holonet.us

assignees: # Users to assign downtime issues (optional)
  - ReArmedHalo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /holonet-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Holonet Upptime Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Holonet Network Uptime and Monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
